name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule: 
   - cron: '0 4 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: main
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: spliit-app/spliit
        upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_SECRET }}
    - name: Checkout patch branch
      uses: actions/checkout@v4
      with:
        ref: main-patch
        sparse-checkout: |
          manifest.webmanifest
          screenshot-wide.jpg
          screenshot.jpg
        sparse-checkout-cone-mode: false

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/aleritty/spliit:latest
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: aleritty
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push the docker image to ghcr.io
      run: docker push ghcr.io/aleritty/anchr:latest
